In [1]:

import pandas as pd
import math
import numpy as np
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import f1_score,accuracy_score,r2_score,mean_squared_error
import warnings
warnings.filterwarnings("ignore")

In [2]:
train=pd.read_csv(r"C:\Users\amany\Desktop\Black_Friday_Sales_prediction\train.csv")
test=pd.read_csv(r"C:\Users\amany\Desktop\Black_Friday_Sales_prediction\test.csv")
original_train = train.copy()
original_test = test.copy()

In [3]:
print(train.shape)
train.isnull().sum()

(550068, 12)


User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [4]:
# train['Age'] = train['Age'].astype('category')
# dummy = pd.get_dummies(train['Age'])
# train = pd.concat((train,dummy),axis=1)
# train=train.drop(['Age','55+','26-35','36-45','46-50','51-55','18-25',],axis=1)
# train=train.rename(columns={"0-17":"Age"})


train.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object

In [5]:
train["Product_Category_2"].fillna(train["Product_Category_2"].median(), inplace=True)
train["Product_Category_3"].fillna(train["Product_Category_3"].median(), inplace=True)

#test

test["Product_Category_2"].fillna(train["Product_Category_2"].median(), inplace=True)
test["Product_Category_3"].fillna(train["Product_Category_3"].median(), inplace=True)

In [6]:
train.isnull().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

In [7]:
test.isnull().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
dtype: int64

In [8]:

train=train.drop('Product_ID',axis=1)
test=test.drop('Product_ID',axis=1)

for label, content in train.items():
    if pd.api.types.is_string_dtype(content):
        print(label)

Gender
Age
City_Category
Stay_In_Current_City_Years


In [9]:
X=train.drop('Purchase',axis=1)
y=train['Purchase']

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((440054, 10), (440054,), (110014, 10), (110014,))

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Age", "Gender", "City_Category", "Stay_In_Current_City_Years"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot, 
                                 categorical_features)],
                                remainder = "passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X.shape

(550068, 23)

In [12]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0       1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  ...  0.0  1.0  0.0   
1       1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  ...  0.0  1.0  0.0   
2       1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  ...  0.0  1.0  0.0   
3       1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  ...  0.0  1.0  0.0   
4       0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
550063  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  1.0  0.0  0.0   
550064  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  1.0   
550065  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
550066  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  ...  0.0  1.0  0.0   
550067  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   

         16         17    18   19    20    21    22  
0       0.0  1000001.0  10.0  0.0   3.0   9.0  14.0  
1       0.0  1000001.0  10.0  0.0   1.0   6.0  14.0  
2       0.0  1000001.0  10.0  0.0  12.0   9.0  14.0  
3       0.0  1000001.0  10.0  0.0  12.0  14.0  14.0  
4       1.0  1000002.0  16.0  0.0   8.0   9.0  14.0  
...     ...        ...   ...  ...   ...   ...   ...  
550063  0.0  1006033.0  13.0  1.0  20.0   9.0  14.0  
550064  0.0  1006035.0   1.0  0.0  20.0   9.0  14.0  
550065  1.0  1006036.0  15.0  1.0  20.0   9.0  14.0  
550066  0.0  1006038.0   1.0  0.0  20.0   9.0  14.0  
550067  1.0  1006039.0   0.0  1.0  20.0   9.0  14.0  

[550068 rows x 23 columns]

In [13]:
X_train,X_test,y_train,y_test = train_test_split(transformed_X,y, test_size=0.2)

In [14]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_jobs=-1,
                              random_state=42,
                               min_samples_split=6,
                               min_samples_leaf=7,
                               max_features=0.5,
                               n_estimators=60,
                               max_depth=None
                               )
model.fit(X_train, y_train)

# %time
# from sklearn.model_selection import RandomizedSearchCV

# # # Different RandomForestRegressor hyperparameters
# rf_grid = {"n_estimators":np.arange(10,100,10),
#             "max_depth": [None,3,5,10],
#             "min_samples_split":np.arange(2,20,2),
#             "min_samples_leaf":np.arange(1,20,2),
#             "max_features":[0.5,1,"sqrt","auto"]}

#  # Instantiate RandomizedSearchCV
# model = RandomizedSearchCV(RandomForestRegressor(n_jobs=-1,
#                                                      random_state=42),
#                                param_distributions=rf_grid,
#                                n_iter=200,
#                                cv=5,
#                                verbose=True)

#  # Fit the RandomizedSearchCV model
# model.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features=0.5, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=7, min_samples_split=6,
                      min_weight_fraction_leaf=0.0, n_estimators=60, n_jobs=-1,
                      oob_score=False, random_state=42, verbose=0,
                      warm_start=False)

In [15]:
lin_pred = model.predict(X_test)
lin_pred

array([10914.25327747,  6762.32652596,  8726.37052971, ...,
       15198.59870407,  5701.96264012,  6571.16724129])

In [16]:
m=mean_squared_error(y_test,lin_pred)
rmse = math.sqrt(m)
rmse

2824.911250896955

In [17]:
#Applying on TEST DATA

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Age", "Gender", "City_Category", "Stay_In_Current_City_Years"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot, 
                                 categorical_features)],
                                remainder = "passthrough")
transformed_X1 = transformer.fit_transform(test)
transformed_X1

array([[ 0.,  0.,  0., ...,  1., 11., 14.],
       [ 0.,  0.,  1., ...,  3.,  5., 14.],
       [ 0.,  0.,  0., ...,  5., 14., 14.],
       ...,
       [ 0.,  0.,  1., ...,  1.,  5., 12.],
       [ 0.,  0.,  0., ..., 10., 16., 14.],
       [ 0.,  0.,  0., ...,  4.,  5., 14.]])

In [18]:
pd.DataFrame(transformed_X1)

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0       0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0  0.0   
1       0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
2       0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
3       0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
4       0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  1.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
233594  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
233595  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
233596  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
233597  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
233598  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   

         16         17    18   19    20    21    22  
0       0.0  1000004.0   7.0  1.0   1.0  11.0  14.0  
1       0.0  1000009.0  17.0  0.0   3.0   5.0  14.0  
2       1.0  1000010.0   1.0  1.0   5.0  14.0  14.0  
3       1.0  1000010.0   1.0  1.0   4.0   9.0  14.0  
4       0.0  1000011.0   1.0  0.0   4.0   5.0  12.0  
...     ...        ...   ...  ...   ...   ...   ...  
233594  1.0  1006036.0  15.0  1.0   8.0   9.0  14.0  
233595  1.0  1006036.0  15.0  1.0   5.0   8.0  14.0  
233596  1.0  1006036.0  15.0  1.0   1.0   5.0  12.0  
233597  1.0  1006037.0   1.0  0.0  10.0  16.0  14.0  
233598  1.0  1006039.0   0.0  1.0   4.0   5.0  14.0  

[233599 rows x 23 columns]

In [19]:
lin_pred_test = model.predict(transformed_X1)
lin_pred_test

array([15744.35512769,  9374.86439689,  7605.90458401, ...,
       12332.41943935, 17239.19351276,  2465.42657213])

In [20]:
sub=pd.read_csv(r"C:\Users\amany\Desktop\blackresult.csv")

In [21]:
sub["Purchase"]=lin_pred_test
sub["User_ID"]=original_test["User_ID"]
sub["Product_ID"]=original_test["Product_ID"]

In [22]:
sub.to_csv('Black_Friday_Result.csv', index=False)

In [23]:
sub

Purchase  User_ID Product_ID
0       15744.355128  1000004  P00128942
1        9374.864397  1000009  P00113442
2        7605.904584  1000010  P00288442
3        2766.467913  1000010  P00145342
4        2845.629468  1000011  P00053842
...              ...      ...        ...
233594   6812.935808  1006036  P00118942
233595   5699.802645  1006036  P00254642
233596  12332.419439  1006036  P00031842
233597  17239.193513  1006037  P00124742
233598   2465.426572  1006039  P00316642

[233599 rows x 3 columns]

In [25]:
#model.best_params_  #For n_iter=200 