# Importing DataFrame


In [1]:
import pandas as pd
dataframe = pd.DataFrame()
dataframe['Name'] = ['AMAN YADAV','PALAK RAGHUWANSHI','SHIVANI MALOKAL','KOMAL YADAV','JAYA RAGHUWANSHI','VAISHNAVI VISHWKARMA','ANUSHKA YADAV']
dataframe['id']   = [991248,991458,32,67,56,'NAN',66]
dataframe['Year'] = ['1st','1st','2nd','3rd','2nd','1st','4th']
dataframe['Holiday']= ['Yes','Yes','Yes','No','Yes','Yes','No']
print(dataframe)
#print(dataframe.head())
print(dataframe.shape)
print(dataframe.describe())

                   Name      id Year Holiday
0            AMAN YADAV  991248  1st     Yes
1     PALAK RAGHUWANSHI  991458  1st     Yes
2       SHIVANI MALOKAL      32  2nd     Yes
3           KOMAL YADAV      67  3rd      No
4      JAYA RAGHUWANSHI      56  2nd     Yes
5  VAISHNAVI VISHWKARMA     NAN  1st     Yes
6         ANUSHKA YADAV      66  4th      No
(7, 4)
                 Name  id Year Holiday
count               7   7    7       7
unique              7   7    4       2
top     ANUSHKA YADAV  66  1st     Yes
freq                1   1    3       5


# Append

In [2]:
new_person = pd.Series(['Shoray Choudary',991253,'1st','Yes'],index=['Name','id','Year','Holiday'])
dataframe.append(new_person,ignore_index=True)


Name      id Year Holiday
0            AMAN YADAV  991248  1st     Yes
1     PALAK RAGHUWANSHI  991458  1st     Yes
2       SHIVANI MALOKAL      32  2nd     Yes
3           KOMAL YADAV      67  3rd      No
4      JAYA RAGHUWANSHI      56  2nd     Yes
5  VAISHNAVI VISHWKARMA     NAN  1st     Yes
6         ANUSHKA YADAV      66  4th      No
7       Shoray Choudary  991253  1st     Yes

# Navigating Dataframes

Select a individual data or slices of dataframes

In [3]:
import pandas as pd
dataframe = pd.DataFrame()
dataframe['Name'] = ['AMAN YADAV','PALAK RAGHUWANSHI','SHIVANI MALOKAL','KOMAL YADAV','JAYA RAGHUWANSHI','VAISHNAVI VISHWKARMA','ANUSHKA YADAV']
dataframe['id']   = [991248,991458,32,67,56,'NAN',66]
dataframe['Year'] = ['1st','1st','2nd','3rd','2nd','1st','4th']
dataframe['Holiday']= ['Yes','Yes','Yes','No','Yes','Yes','No']
dataframe.iloc[0] 

Name       AMAN YADAV
id             991248
Year              1st
Holiday           Yes
Name: 0, dtype: object

In [4]:
dataframe.iloc[1] 

Name       PALAK RAGHUWANSHI
id                    991458
Year                     1st
Holiday                  Yes
Name: 1, dtype: object

In [5]:
dataframe.iloc[0:2] 

Name      id Year Holiday
0         AMAN YADAV  991248  1st     Yes
1  PALAK RAGHUWANSHI  991458  1st     Yes

In [6]:
dataframe.loc[0] 

Name       AMAN YADAV
id             991248
Year              1st
Holiday           Yes
Name: 0, dtype: object

In [7]:
dataframe.loc[0:2]

Name      id Year Holiday
0         AMAN YADAV  991248  1st     Yes
1  PALAK RAGHUWANSHI  991458  1st     Yes
2    SHIVANI MALOKAL      32  2nd     Yes

# Selecting rows based on condition

In [87]:
import pandas as pd

dataframe = pd.DataFrame()
dataframe['Name'] = ['AMAN YADAV','PALAK RAGHUWANSHI','SHIVANI MALOKAL','KOMAL YADAV','JAYA RAGHUWANSHI','VAISHNAVI VISHWKARMA','ANUSHKA YADAV']
dataframe['id']   = [991248,991458,32,67,56,'NAN',66]
dataframe['Year'] = ['1st','1st','2nd','3rd','2nd','1st','4th']
dataframe['Holiday']= ['Yes','Yes','Yes','No','Yes','Yes','No']

dataframe[dataframe['Year'] == '1st']                   #without importing this time it is possible

Name      id Year Holiday
0            AMAN YADAV  991248  1st     Yes
1     PALAK RAGHUWANSHI  991458  1st     Yes
5  VAISHNAVI VISHWKARMA     NAN  1st     Yes

In [9]:
dataframe[dataframe['Name'] != 'AMAN YADAV']

Name      id Year Holiday
1     PALAK RAGHUWANSHI  991458  1st     Yes
2       SHIVANI MALOKAL      32  2nd     Yes
3           KOMAL YADAV      67  3rd      No
4      JAYA RAGHUWANSHI      56  2nd     Yes
5  VAISHNAVI VISHWKARMA     NAN  1st     Yes
6         ANUSHKA YADAV      66  4th      No

# Replacing Values

In [91]:
import pandas as pd

dataframe = pd.DataFrame()
dataframe['Name'] = ['AMAN YADAV','PALAK RAGHUWANSHI','SHIVANI MALOKAL','KOMAL YADAV','JAYA RAGHUWANSHI','VAISHNAVI VISHWKARMA','ANUSHKA YADAV']
dataframe['id']   = [991248,991458,32,67,56,'NAN',66]
dataframe['Year'] = ['1st','1st','2nd','3rd','2nd','1st','4th']
dataframe['Holiday']= ['Yes','Yes','Yes','No','Yes','Yes','No']

dataframe['id'].replace(['NAN', '0'],[32,45])            #Two ways of writing repalce 

0    991248
1    991458
2        32
3        67
4        56
5        32
6        66
Name: id, dtype: object

In [11]:
type(dataframe)

pandas.core.frame.DataFrame

In [95]:
dataframe.replace(r'4th', 'one',regex=True)  
dataframe.replace(r'NAN', 32,regex=True) 

Name      id Year Holiday
0            AMAN YADAV  991248  1st     Yes
1     PALAK RAGHUWANSHI  991458  1st     Yes
2       SHIVANI MALOKAL      32  2nd     Yes
3           KOMAL YADAV      67  3rd      No
4      JAYA RAGHUWANSHI      56  2nd     Yes
5  VAISHNAVI VISHWKARMA      32  1st     Yes
6         ANUSHKA YADAV      66  4th      No

In [13]:
dataframe

Name      id Year Holiday
0            AMAN YADAV  991248  1st     Yes
1     PALAK RAGHUWANSHI  991458  1st     Yes
2       SHIVANI MALOKAL      32  2nd     Yes
3           KOMAL YADAV      67  3rd      No
4      JAYA RAGHUWANSHI      56  2nd     Yes
5  VAISHNAVI VISHWKARMA     NAN  1st     Yes
6         ANUSHKA YADAV      66  4th      No

# Renaming columns

In [100]:
dataframe.rename(columns={'Holiday':'Vacation','id':'id2'})      #we can change the multi col simultaneously.

Name     id2 Year Vacation
0            AMAN YADAV  991248  1st      Yes
1     PALAK RAGHUWANSHI  991458  1st      Yes
2       SHIVANI MALOKAL      32  2nd      Yes
3           KOMAL YADAV      67  3rd       No
4      JAYA RAGHUWANSHI      56  2nd      Yes
5  VAISHNAVI VISHWKARMA     NAN  1st      Yes
6         ANUSHKA YADAV      66  4th       No

In [15]:
import pandas as pd

dataframe = pd.DataFrame()
dataframe['Name'] = ['AMAN YADAV','PALAK RAGHUWANSHI','SHIVANI MALOKAL','KOMAL YADAV','JAYA RAGHUWANSHI','VAISHNAVI VISHWKARMA','ANUSHKA YADAV']
dataframe['id']   = [991248,991458,32,67,56,88,66]
dataframe['Year'] = ['1st','1st','2nd','3rd','2nd','1st','4th']
dataframe['Holiday']= ['Yes','Yes','Yes','No','Yes','Yes','No']

print(dataframe['id'].min())
print(dataframe['id'].max())
print(dataframe['id'].mean())
print(dataframe['id'].sum())
print(dataframe['id'].count())

32
991458
283287.85714285716
1983015
7


In [16]:
dataframe['id'].value_counts()

56        1
66        1
88        1
32        1
67        1
991458    1
991248    1
Name: id, dtype: int64

In [17]:
dataframe['id'].nunique()

7

In [18]:
import pandas as pd

dataframe = pd.DataFrame()
dataframe['Name'] = ['AMAN YADAV','PALAK RAGHUWANSHI','SHIVANI MALOKAL','KOMAL YADAV','JAYA RAGHUWANSHI','VAISHNAVI VISHWKARMA','ANUSHKA YADAV']
dataframe['id']   = [991248,991458,32,67,'NAN',88,66]
dataframe['Year'] = ['1st','1st','2nd','3rd','2nd','NAN','4th']
dataframe['Holiday']= ['Yes','Yes','Yes','No','Yes','Yes','No']

dataframe[dataframe['id'].isnull()]

Empty DataFrame
Columns: [Name, id, Year, Holiday]
Index: []


# Deleting a coloumn

In [19]:
dataframe.drop('id',axis=1)
dataframe.drop(['id','Year'],axis=1)

Name Holiday
0            AMAN YADAV     Yes
1     PALAK RAGHUWANSHI     Yes
2       SHIVANI MALOKAL     Yes
3           KOMAL YADAV      No
4      JAYA RAGHUWANSHI     Yes
5  VAISHNAVI VISHWKARMA     Yes
6         ANUSHKA YADAV      No

In [101]:
dataframe.drop([dataframe.columns[2]],axis=1)

Name      id Holiday
0            AMAN YADAV  991248     Yes
1     PALAK RAGHUWANSHI  991458     Yes
2       SHIVANI MALOKAL      32     Yes
3           KOMAL YADAV      67      No
4      JAYA RAGHUWANSHI      56     Yes
5  VAISHNAVI VISHWKARMA     NAN     Yes
6         ANUSHKA YADAV      66      No

# Groupby values

In [21]:
dataframe.groupby('Year').min()

Name Holiday
Year                              
1st             AMAN YADAV     Yes
2nd       JAYA RAGHUWANSHI     Yes
3rd            KOMAL YADAV      No
4th          ANUSHKA YADAV      No
NAN   VAISHNAVI VISHWKARMA     Yes

# Grouping rows by time

In [22]:
import numpy as np
import pandas as pd
dt = pd.date_range('08/04/2020', periods = 25 , freq='SM')#W,SM,30S,3T,Q M(TIME PERIOD)
df=pd.DataFrame(index=dt)
df['amount']=np.random.randint(1,500,25)
print(df)
print(df.resample('3T').sum())

            amount
2020-08-15      25
2020-08-31     356
2020-09-15     123
2020-09-30     454
2020-10-15      61
2020-10-31      99
2020-11-15     122
2020-11-30      38
2020-12-15     136
2020-12-31      61
2021-01-15     167
2021-01-31     405
2021-02-15      23
2021-02-28     277
2021-03-15      11
2021-03-31     301
2021-04-15     252
2021-04-30     444
2021-05-15     316
2021-05-31     169
2021-06-15     348
2021-06-30     246
2021-07-15      13
2021-07-31     494
2021-08-15     461
                     amount
2020-08-15 00:00:00      25
2020-08-15 00:03:00       0
2020-08-15 00:06:00       0
2020-08-15 00:09:00       0
2020-08-15 00:12:00       0
...                     ...
2021-08-14 23:48:00       0
2021-08-14 23:51:00       0
2021-08-14 23:54:00       0
2021-08-14 23:57:00       0
2021-08-15 00:00:00     461

[175201 rows x 1 columns]


# concatanation of dataframe


In [104]:
import pandas as pd
data_a = {'id':[99,11,23],
          'Name':['Ag','Og','BOg']
}
dataframe_2= pd.DataFrame(data_a,columns=['id','Name'])
data=pd.concat([dataframe,dataframe_2],axis=0,ignore_index=True)
print(data)
print(data.isnull().sum())

  Holiday                  Name Year      id
0     Yes            AMAN YADAV  1st  991248
1     Yes     PALAK RAGHUWANSHI  1st  991458
2     Yes       SHIVANI MALOKAL  2nd      32
3      No           KOMAL YADAV  3rd      67
4     Yes      JAYA RAGHUWANSHI  2nd      56
5     Yes  VAISHNAVI VISHWKARMA  1st     NAN
6      No         ANUSHKA YADAV  4th      66
7     NaN                    Ag  NaN      99
8     NaN                    Og  NaN      11
9     NaN                   BOg  NaN      23
Holiday    3
Name       0
Year       3
id         0
dtype: int64


F:\anaconda\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


# Encoding Nominal categorical data

In [24]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer,MultiLabelBinarizer

feature = np.array([['AMfferewrAN'],
                  ['YAwerrwrDAV'],['kcndakjn'],['dsnsdn']])
one_hot =  LabelBinarizer()
one_hot.fit_transform(feature)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

In [25]:
one_hot.classes_

array(['AMfferewrAN', 'YAwerrwrDAV', 'dsnsdn', 'kcndakjn'], dtype='<U11')

In [109]:
import pandas as pd 
pd.get_dummies(feature[:,0])

SyntaxError: invalid syntax (<ipython-input-109-89c9c828f69a>, line 2)

In [27]:
mul_feature = [("AMAN","PALAK"),
              ("YADAV","RAGHUWANSHI"),
              ("k.dnew","hwefhewih")]
one_hot =  MultiLabelBinarizer()
one_hot.fit_transform(mul_feature)

array([[1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1]])

In [28]:
pd.get_dummies(mul_feature[:])

(AMAN, PALAK)  (YADAV, RAGHUWANSHI)  (k.dnew, hwefhewih)
0              1                     0                    0
1              0                     1                    0
2              0                     0                    1

# Encoding ordinal categorical  features

In [29]:
data=pd.DataFrame({'Compliments' : ['Ravishing','Debonair','pretty','beautiful']})
scale = {'Ravishing':1,
        'Debonair': 2,
        'pretty':3,
        'beautiful':4}
data['Compliments'].replace(scale)

0    1
1    2
2    3
3    4
Name: Compliments, dtype: int64

# Encoding dictionaries of features

In [30]:
from sklearn.feature_extraction import DictVectorizer
data1=[{"red" : 1, "blue"  : 4},
      {"orange": 77 , "purple":7}]
dictV =  DictVectorizer(sparse=False)
dictV.fit_transform(data1)

array([[ 4.,  0.,  0.,  1.],
       [ 0., 77.,  7.,  0.]])

In [31]:
dictV.get_feature_names()

['blue', 'orange', 'purple', 'red']

In [32]:
pd.DataFrame(dictV.fit_transform(data1) , columns=dictV.get_feature_names())

blue  orange  purple  red
0   4.0     0.0     0.0  1.0
1   0.0    77.0     7.0  0.0

# Rescaling the feature

In [33]:
import numpy as np
from sklearn import preprocessing
feature = np.array([[34757],[4435],[4550],[0],[765],[6576],[65754]])
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,1)) #we can change range 
scaled_feature = minmax_scale.fit_transform(feature)
print(scaled_feature) 
print(minmax_scale)

[[0.52859142]
 [0.06744837]
 [0.06919731]
 [0.        ]
 [0.01163427]
 [0.10000912]
 [1.        ]]
MinMaxScaler(copy=True, feature_range=(0, 1))


# standardizing a feature

You want to transform a feature to have a mean of 0 and standard deviation of 1

In [34]:
x = np.array([[-4334.3],[47443],[5633],[5345342]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
standardized

array([[-0.58624865],
       [-0.56381138],
       [-0.5819294 ],
       [ 1.73198944]])

In [35]:
print("Mean: ",round(standardized.mean()))
print("standard deviation: ",standardized.std())

Mean:  0.0
standard deviation:  0.9999999999999999


# Normalizing Observation

You want to rescale the feature values of observations to have unit norm(a total length of 1)

In [36]:
# import numpy as np
from sklearn.preprocessing import Normalizer

features = np.array([[0.5,0.5],[1.1,3.4],[1.5,20.4],[1.63,34.3]])
normalizer = Normalizer(norm = "l2")
normalizer.fit_transform(features)
#The L2 norm calculates the distance of the vector
#coordinate from the origin of the vector space.
#As such, it is also known as the Euclidean norm as it
#is calculated as the Euclidean distance from the origin.
#The result is a positive distance value.

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07333144, 0.99730763],
       [0.0474683 , 0.99887275]])

# Generating polynomial and interaction features

you want to create polynomial and interaction features

In [37]:
from sklearn.preprocessing import PolynomialFeatures
features = np.array([[2,3],[3,4],[4,5],[8,7]])
polynomial_interaction = PolynomialFeatures(degree=2, include_bias = False)
polynomial_interaction.fit_transform(features)

array([[ 2.,  3.,  4.,  6.,  9.],
       [ 3.,  4.,  9., 12., 16.],
       [ 4.,  5., 16., 20., 25.],
       [ 8.,  7., 64., 56., 49.]])

In [38]:
interaction = PolynomialFeatures(degree=2,interaction_only =True, include_bias=False)
interaction.fit_transform(features)

array([[ 2.,  3.,  6.],
       [ 3.,  4., 12.],
       [ 4.,  5., 20.],
       [ 8.,  7., 56.]])

# Transforming Features

You wanna make a custom transformation to one or more features

In [39]:
from sklearn.preprocessing import FunctionTransformer
features = np.array([[2,3],[4,5],[3,6]])
def add(x):
    return x +10    #index change possible
add_transformer = FunctionTransformer(add)
add_transformer.fit_transform(features)

F:\anaconda\lib\site-packages\sklearn\preprocessing\_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)
F:\anaconda\lib\site-packages\sklearn\preprocessing\_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)


array([[12, 13],
       [14, 15],
       [13, 16]])

In [40]:
import pandas as pd
df = pd.DataFrame(features,columns=["feature_1","feature_2"])
df.apply(add)

feature_1  feature_2
0         12         13
1         14         15
2         13         16

# Detecting Outliars

Outliers are extreme values that deviate from other observations on data , they may indicate a variability in a measurement, experimental errors or a novelty. In other words, an outlier is an observation that diverges from an overall pattern on a sample.
you wanna identify extreme observation

In [41]:
import numpy as np
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

features, _ = make_blobs(n_samples = 10,
                        n_features = 2 ,
                        centers = 1,
                        random_state =1)
features[0,0]=10000
features[0,1]=10000

outlier_detector = EllipticEnvelope(contamination=.1)
outlier_detector.fit(features)
outlier_detector.predict(features)
#print(features.shape)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [42]:
feature = features[:,0]
 
def indicies_of_outliars(x):
    q1,q3=np.percentile(x,[25,75])
    iqr = q3-q1
    lower_bound = q1-(iqr*3)
    upper_bound = q3+(iqr*3)
    return np.where((x>upper_bound) | (x<lower_bound))
indicies_of_outliars(feature)

(array([0], dtype=int64),)

# Handling outliars

In [43]:
import pandas as pd
houses = pd.DataFrame()
houses['price'] = [434434,232324,565432,223334]
houses['bathroom'] = [4,2,5,24]
houses['square feet'] = [4000,2000,5000,24000]
houses[houses['bathroom']<20]

price  bathroom  square feet
0  434434         4         4000
1  232324         2         2000
2  565432         5         5000

In [44]:
import numpy as np
houses['Outliar']=np.where(houses['bathroom']<20,0,1)
houses

price  bathroom  square feet  Outliar
0  434434         4         4000        0
1  232324         2         2000        0
2  565432         5         5000        0
3  223334        24        24000        1

In [45]:
houses['log of sq feet']=[np.log(x) for x in houses['square feet']]
houses

price  bathroom  square feet  Outliar  log of sq feet
0  434434         4         4000        0        8.294050
1  232324         2         2000        0        7.600902
2  565432         5         5000        0        8.517193
3  223334        24        24000        1       10.085809

# Discretizating Features
you have a numerival feature and wanna break it up into discrete bins

In [46]:
import numpy as np 
from sklearn.preprocessing import Binarizer
age = np.array([[4],[5],[13],[45],[65]])
binarizer = Binarizer(24)
binarizer.fit_transform(age)

array([[0],
       [0],
       [0],
       [1],
       [1]])

In [47]:
np.digitize(age,bins=[30,63])

array([[0],
       [0],
       [0],
       [1],
       [2]], dtype=int64)

# Grouping Observation using clustering
you wanna cluster observations so that similar observation are grouped together

In [48]:
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
features, _ = make_blobs(n_samples = 50,
                        n_features = 2 ,
                        centers = 30,
                        random_state =1)
dataframe = pd.DataFrame(features,columns=["feature1","feature2"])
clusterer = KMeans(4,random_state=0)
clusterer.fit_transform(features)
dataframe['group']=clusterer.predict(features)
dataframe.head()

feature1  feature2  group
0  2.464425 -3.374528      0
1 -1.851395  3.518861      1
2 -1.779063  1.661476      1
3 -1.338269 -0.848405      0
4 -9.793462  0.194035      2

# VECTOR, MATRIX AND ARRAY

In [49]:
import numpy as np
vector = np.array([[1,2],
                  [2,4],
                  [3,6]])
vector

array([[1, 2],
       [2, 4],
       [3, 6]])

In [50]:
vector = np.mat([[1,2],
                  [2,4],
                  [3,6]])
vector

matrix([[1, 2],
        [2, 4],
        [3, 6]])

In [51]:
from scipy import sparse
vector = np.mat([[10,0],
                  [0,4],
                  [3,0]])
matrix_sparse = sparse.csr_matrix(vector)   
print(matrix_sparse)

  (0, 0)	10
  (1, 1)	4
  (2, 0)	3


# slicing in matrix

In [52]:
vector = np.mat([[10,0],
                  [0,4],
                  [3,9]])
vector[1,1]

4

In [53]:
vector[0,1]

0

In [54]:
vector[:]

matrix([[10,  0],
        [ 0,  4],
        [ 3,  9]])

In [55]:
vector[1:,0]

matrix([[0],
        [3]])

# shape, size and dimension of matrix

In [56]:
import numpy as np
mat = np.mat([[2,4,6,8],
             [1,3,5,8],
             [4,5,3,6],
             [9,0,3,6]])
mat.shape

(4, 4)

In [57]:
mat.size

16

In [58]:
mat.ndim

2

# apply some function in array

In [59]:
mat = np.mat([[2,4,6,8],
             [1,3,5,8],
             [4,5,3,6],
             [9,0,3,6]])
add = lambda i:i+100
vectorized = np.vectorize(add)
vectorized(mat)

matrix([[102, 104, 106, 108],
        [101, 103, 105, 108],
        [104, 105, 103, 106],
        [109, 100, 103, 106]])

In [60]:
mat+100

matrix([[102, 104, 106, 108],
        [101, 103, 105, 108],
        [104, 105, 103, 106],
        [109, 100, 103, 106]])

In [61]:
mat = np.mat([[2,4,6,8],
             [1,3,40,0],
             [4,51,3,96],
             [9,0,3,6]])
np.max(mat)

96

In [62]:
np.min(mat)

0

In [63]:
np.max(mat,axis=0)

matrix([[ 9, 51, 40, 96]])

In [64]:
np.max(mat,axis=1)

matrix([[ 8],
        [40],
        [96],
        [ 9]])

#  Average, variance, standard deviation,reshaping and flatten 

In [65]:
mat = np.mat([[2,4,6,8],
             [1,3,40,0],
             [4,51,3,96],
             [9,0,3,6]])
#mat.mean()
np.mean(mat)

14.75

In [66]:
mat.var()

638.5625

In [67]:
mat.std()

25.269794221560254

In [68]:
mat.reshape(2,8)

matrix([[ 2,  4,  6,  8,  1,  3, 40,  0],
        [ 4, 51,  3, 96,  9,  0,  3,  6]])

In [69]:
mat.reshape(1,-1)

matrix([[ 2,  4,  6,  8,  1,  3, 40,  0,  4, 51,  3, 96,  9,  0,  3,  6]])

In [70]:
mat.flatten()

matrix([[ 2,  4,  6,  8,  1,  3, 40,  0,  4, 51,  3, 96,  9,  0,  3,  6]])

# Rank of matrix and determinent

In [71]:
mat = np.mat([[2,4,6,8],
             [1,3,40,0],
             [4,51,3,96],
             [0,3,0,2]])
np.linalg.matrix_rank(mat)

4

In [72]:
np.linalg.det(mat)

11143.999999999984

# Getting diagonal and trace (sum of diagonal)

In [73]:
mat = np.mat([[2,4,6,8],
             [1,3,40,0],
             [4,51,3,96],
             [0,3,0,2]])
mat.diagonal()

matrix([[2, 3, 3, 2]])

In [74]:
mat.trace()

matrix([[10]])

In [75]:
mat.diagonal(offset=1)

matrix([[ 4, 40, 96]])

In [76]:
mat.diagonal(offset=2)

matrix([[6, 0]])

In [77]:
mat.diagonal(offset=-2)

matrix([[4, 3]])

# EiganValues and EiganVectors of matrix

In [78]:
mat = np.mat([[2,4,6,8],
             [1,3,40,0],
             [4,51,3,96],
             [0,3,0,2]])
eiganvalue,eiganvector = np.linalg.eig(mat)

In [79]:
eiganvalue

array([ 51.20337438, -39.04357913,   1.51635193,  -3.67614718])

In [80]:
eiganvector

matrix([[ 0.15022642,  0.04857191,  0.9986381 , -0.19090214],
        [ 0.63270227,  0.68698927,  0.00726777, -0.85793516],
        [ 0.75870395, -0.72330149, -0.02523552,  0.14796509],
        [ 0.03857676, -0.05021413, -0.04508091,  0.45344235]])

# Add,sub,multiply and dot product

In [81]:
mat_1 = np.array([2,3,4])
mat_2 = np.array([3,4,5])
np.dot(mat_1,mat_2)

38

In [82]:
mat_1 @ mat_2

38

In [83]:
np.add(mat_1,mat_2)

array([5, 7, 9])

In [84]:
np.subtract(mat_1,mat_2)

array([-1, -1, -1])

In [85]:
np.multiply(mat_1,mat_2)

array([ 6, 12, 20])

In [86]:
mat_1 = np.array([[1,1],
                 [1,2]])
mat_2 = np.array([[1,3],
                 [1,2]])
np.multiply(mat_1,mat_2)  #for multiplication we use dot in place of multiply

array([[1, 3],
       [1, 4]])